language: python

cache: pip

branches:
  only:
  - master

jobs:
  include:
  - python: "2.7"
    env: TOXENV=py27-sphinx18
  - python: "3.5"
    env: TOXENV=py35-sphinx18
  - python: "3.5"
    env: TOXENV=py35-sphinx22
  - python: "3.5"
    env: TOXENV=py35-sphinx23
  - python: "3.5"
    env: TOXENV=py35-sphinx24
  - python: "3.5"
    env: TOXENV=py35-sphinx30
  - python: "3.5"
    env: TOXENV=py35-sphinx31
  - python: "3.6"
    env: TOXENV=py36-sphinx18
  - python: "3.6"
    env: TOXENV=py36-sphinx22
  - python: "3.6"
    env: TOXENV=py36-sphinx23
  - python: "3.6"
    env: TOXENV=py36-sphinx24
  - python: "3.6"
    env: TOXENV=py36-sphinx30
  - python: "3.6"
    env: TOXENV=py36-sphinx31
  - python: "3.7"
    env: TOXENV=py37-sphinx18
    dist: xenial
  - python: "3.7"
    env: TOXENV=py37-sphinx22
    dist: xenial
  - python: "3.7"
    env: TOXENV=py37-sphinx23
    dist: xenial
  - python: "3.7"
    env: TOXENV=py37-sphinx24
    dist: xenial
  - python: "3.7"
    env: TOXENV=py37-sphinx30
    dist: xenial
  - python: "3.7"
    env: TOXENV=py37-sphinx31
    dist: xenial
  - python: "3.8"
    env: TOXENV=py38-sphinx18
    dist: bionic
  - python: "3.8"
    env: TOXENV=py38-sphinx22
    dist: bionic
  - python: "3.8"
    env: TOXENV=py38-sphinx23
    dist: bionic
  - python: "3.8"
    env: TOXENV=py38-sphinx24
    dist: bionic
  - python: "3.8"
    env: TOXENV=py38-sphinx30
    dist: bionic
  - python: "3.8"
    env: TOXENV=py38-sphinx31
    dist: bionic
  - os: osx
    env: TOXENV=py27-sphinx18
    language: shell
  - os: osx
    env: TOXENV=py37-sphinx23
    language: shell
    osx_image: xcode10.2 # python 3.7.3
  - os: windows
    env: TOXENV=py27-sphinx18
    language: shell
    before_install:
      - choco install python2
      - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
  - os: windows
    env: TOXENV=py38-sphinx31
    language: shell
    before_install:
      - choco install python3 --params "/InstallDir:C:\Python" --version=3.8.0
      - export PATH="/c/Python:/c/Python/Scripts:$PATH"
  - python: "3.8"
    env: TOXENV=pylint
  - python: "3.8"
    env: TOXENV=flake8

install:
 - pip install --upgrade tox

script:
 - tox

notifications:
  email: false
